name: JHAiPayRailz ADMIN Permissions Audit

on:
  workflow_dispatch:
  schedule:
    # Runs on every Sunday at 00:00 UTC
    #
    #        ┌────────────── minute
    #        │ ┌──────────── hour
    #        │ │ ┌────────── day (month)
    #        │ │ │ ┌──────── month
    #        │ │ │ │ ┌────── day (week)
    - cron: '30 2 30 * *'

jobs:
  github-collaborator-report:
    runs-on: ubuntu-latest
    timeout-minutes: 3000
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get repo collaborator report
        uses: JHAAdmins/github-org-repo-collaborator-action@v2.2
        with:
          token: ${{ secrets.GITHUBREPOPERMS }}
          org: 'JHAiPayRailz'
          affil: 'ALL'
          permission: 'ADMIN'
          json: 'FALSE'
          appid: ${{ secrets.APPID }}
          privatekey: ${{ secrets.PRIVATEKEY }}
          installationid: ${{ secrets.INSTALLATIONID }}
